version: "3"

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wp_volume:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    restart: always
    env_file: .env
    volumes:
      - wp_volume:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lwray/data/db/
  wp_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lwray/data/wordpress/

networks:
  inception:
    driver: bridge 
    #Bridge networks are usually used when your applications run 
    # in standalone containers that need to communicate